In [1]:
import os
import sys
from pathlib import Path

# setting proper working directory
PROJECT_DIRECTORY = Path(os.path.abspath('')).resolve().parents[0]
sys.path.extend([str(PROJECT_DIRECTORY)])

print(f'Python {sys.version} on {sys.platform}')
print('Project directory: ', PROJECT_DIRECTORY)

Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Project directory:  C:\Users\s8347434\Documents\RecBole-GNN

In [2]:
import pandas as pd
import numpy as np
import ast
import json
from recbole_gnn.config import Config
from recbole_gnn.utils import create_dataset
from recbole_gnn.data.dataset_metrics import GraphDatasetEvaluator
from tqdm import tqdm

#### Read Evaluation Data
- model evaluation from test runs
- data set evaluation (topological characteristics)

In [11]:
dataset_split_characteristics_df = pd.read_csv("../asset/Evaluation/DatasetCharacteristics.csv", sep="\t")
print(dataset_split_characteristics_df.shape)

(177, 37)

In [12]:
dataset_split_characteristics_df['sparsity'] = 1 - dataset_split_characteristics_df['density']
dataset_split_characteristics_df['density_log'] = np.log10(dataset_split_characteristics_df['density'])
dataset_split_characteristics_df['average_clustering_coef_dot_user_log'] = np.log10(dataset_split_characteristics_df['average_clustering_coef_dot_user'])
dataset_split_characteristics_df['average_clustering_coef_dot_item_log'] = np.log10(dataset_split_characteristics_df['average_clustering_coef_dot_item'])

In [13]:
EVAL_RUN = "RO"
als_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/ALS-Benchmark-{EVAL_RUN}.csv", sep="\t")
asym_user_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/AsymUserKNN-Benchmark-{EVAL_RUN}.csv", sep="\t")
asym_item_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/AsymItemKNN-Benchmark-{EVAL_RUN}.csv", sep="\t")
bpr_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/BPR-Benchmark-{EVAL_RUN}.csv", sep="\t")
lightgcn_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/LightGCN-Benchmark-{EVAL_RUN}.csv", sep="\t")
ultragcn_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/UltraGCN-Benchmark-{EVAL_RUN}.csv", sep="\t")
sgl_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/SGL-Benchmark-{EVAL_RUN}.csv", sep="\t")
xsimgcl_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/XSimGCL-Benchmark-{EVAL_RUN}.csv", sep="\t")
pop_df = pd.read_csv(f"log/Benchmark/{EVAL_RUN}/Pop-Benchmark-{EVAL_RUN}.csv", sep="\t")

In [59]:
model_evaluation_df = pd.concat([als_df, asym_user_df, asym_item_df, bpr_df, lightgcn_df, ultragcn_df, sgl_df, xsimgcl_df, pop_df], ignore_index=True)
model_evaluation_df['dataset'] = model_evaluation_df['dataset'].str.extract(r'-(\d+)$').astype(int)
model_evaluation_df["eval_type"] = [EVAL_RUN] * len(model_evaluation_df)
print(model_evaluation_df.shape)

(1585, 21)

In [60]:
# Function to process columns
def process_user_columns(df):
    for col in df.columns:
        if col.startswith('best_user_') or col.startswith('worst_user_') or col.startswith('clustering_coefficients'):
            # Apply transformation for each row in the selected columns
            df[col] = df[col].apply(ast.literal_eval)        
    return df

In [61]:
model_evaluation_df = process_user_columns(model_evaluation_df)

In [62]:
evaluation_dataset_characteristics_df = pd.merge(model_evaluation_df, dataset_split_characteristics_df, on='dataset', how='left')
print(evaluation_dataset_characteristics_df.shape)

(1585, 58)

#### Create necessary Data for Evaluation
- classical characteristics per best / worst user (popularity, interactions)
- topological characteristics per best / worst user
- match userID with global userID

In [64]:
def get_users_topological_chars(data, file_path, num_datasets):    
    
    dataset_eval_list = []
    datasets = evaluation_dataset_characteristics_df['dataset'].head(num_datasets).unique()
    for i in tqdm(datasets, total=len(datasets), unit='datasets'):        
        # mapping recbole ID -> local ID (as recbole resets the index after filtering the datasets)
        config = Config(model="BPR", dataset=f"real-life-atomic-100000-{i}", config_file_list=["config_files/datasets.yaml"])
        dataset = create_dataset(config)

        # Extract unique user IDs from best_user_ and worst_user_ columns
        best_user_ids = set()  # Use a set to ensure uniqueness
        worst_user_ids = set()  # Use a set to ensure uniqueness
        for index, row in data[data['dataset']==i].iterrows():
            for col in data.columns:
                if col.startswith('best_user_'):
                    # Extract user IDs from the list of dictionaries
                    for entry in row[col]:  # Assuming each entry is a list of dictionaries
                        best_user_ids.add(int(list(entry.keys())[0]))  # Add user ID (the key) to the set
                if col.startswith('worst_user_'):
                    # Extract user IDs from the list of dictionaries
                    for entry in row[col]:  # Assuming each entry is a list of dictionaries
                        worst_user_ids.add(int(list(entry.keys())[0]))  # Add user ID (the key) to the set
                                
            #print(best_user_ids)
            #print(worst_user_ids)

        # calculate dataset metrics
        dataset_evaluator = GraphDatasetEvaluator(config, dataset)
        # some metrics need a connected graph and thus drops nodes which are in smallest partition
        dataset_eval_dict = {"dataset": i}
        dataset_eval_dict.update(dataset_evaluator.evaluate_best_worst_users(best_user_ids, worst_user_ids))
        dataset_eval_list.append(dataset_eval_dict)

        df = pd.DataFrame(dataset_eval_list)
        df.to_csv(file_path, sep='\t', index=False)

    return df

In [65]:
# HINT: takes approx. 5h
file_path = f"../asset/Evaluation/{EVAL_RUN}/UserTopologicalChars.csv"
if not os.path.isfile(file_path):
    print("File does not exist, calculate all user's topology characteristics for each dataset..")
    user_topologies_df = get_users_topological_chars(evaluation_dataset_characteristics_df, file_path, num_datasets=176)
else:
    print(f"File exists! Load file from {file_path}")
    user_topologies_df = pd.read_csv(file_path, sep='\t')
    user_topologies_df = process_user_columns(user_topologies_df)

File does not exist, calculate all user's topology characteristics for each dataset..

 64%|██████▍   | 113/176 [3:55:06<2:13:01, 126.69s/datasets]

GraphDatasetEvaluator: the graph is not connected.
GraphDatasetEvaluator: the graph is not connected.
GraphDatasetEvaluator: the graph is not connected. Building the connected subgraph.
The disconnected partitions:  [{1031, 15111, 15113, 14862, 14998, 15002, 15135, 14624, 15141, 15025, 15026, 15041, 15169, 15047, 15048, 15057, 14941, 15071, 15077, 14954, 14973}]
GraphDatasetEvaluator: graph is connected.
GraphDatasetEvaluator: graph characteristics
 nodes: 17702
 edges: 74959
 user nodes: 1319
 item nodes: 16383
GraphDatasetEvaluator: 2 users removed
GraphDatasetEvaluator: 21 items removed

 86%|████████▋ | 152/176 [5:14:00<45:40, 114.20s/datasets]

GraphDatasetEvaluator: the graph is not connected.
GraphDatasetEvaluator: the graph is not connected.
GraphDatasetEvaluator: the graph is not connected. Building the connected subgraph.
The disconnected partitions:  [{9984, 9985, 9986, 9987, 9988, 9989, 9990, 9991, 9993, 9994, 531, 10003, 10006, 9961, 9962, 9963, 9965, 9967, 9968, 9969, 9972, 9973, 9974, 9975, 9976, 9977, 9978, 9979, 9980, 9981, 9982, 9983}]
GraphDatasetEvaluator: graph is connected.
GraphDatasetEvaluator: graph characteristics
 nodes: 20798
 edges: 80963
 user nodes: 1152
 item nodes: 19646
GraphDatasetEvaluator: 2 users removed
GraphDatasetEvaluator: 32 items removed

100%|██████████| 176/176 [6:06:22<00:00, 124.90s/datasets]

In [66]:
# user_topologies_df

### Merge all together

In [67]:
evaluation_dataset_characteristics_user_topologies_df = pd.merge(evaluation_dataset_characteristics_df, user_topologies_df, on='dataset', how='left')

In [68]:
print(evaluation_dataset_characteristics_user_topologies_df.shape)

(1585, 62)

#### Translate the userIDs into the userIDs out of the original dataset
- global ID: the userID which holds through all splits
- local ID: the userID which is only valid within one split
- recbole ID: the userID which is assigned after the filtering

In [69]:
def translate_userids(df, num_rows):      
    # Extract columns ending with @[10]
    data = df.copy()
    columns_to_process = [col for col in data.columns if col.endswith("@[10]")]
    
    for index, row in tqdm(data.iloc[:num_rows].iterrows(), total=num_rows, unit='rows'):
        # configurations initialization
        FILENAME = PROJECT_DIRECTORY / f"asset/data/real-life-atomic-splits/real-life-atomic-100000-{row['dataset']}/real-life-atomic-100000-{row['dataset']}.inter"
        db = pd.read_csv(FILENAME, sep="\t", encoding="utf-8")
        
        # mapping recbole ID -> local ID (as recbole resets the index after filtering the datasets)
        config = Config(model="BPR", dataset=f"real-life-atomic-100000-{row['dataset']}", config_file_list=["config_files/datasets.yaml"])
        dataset = create_dataset(config)
        flipped_dict = {v: k for k, v in dataset.field2token_id['user_id'].items()}

        # mapping local ID -> global ID
        translation_dict = dict(zip(db["user_id:token"], db["userID:token"]))

        # Process each column
        for col in columns_to_process:
            # Parse the string entries and extract the user IDs
            #print(row['Model'], row['dataset'], col)
            new_entry = {str(translation_dict[int(flipped_dict[int(list(entry.keys())[0])])]) : float(list(entry.values())[0]) for entry in row[col]}
            data.at[index, col] = new_entry
            
    return data

In [70]:
# HINT: takes approx. 20-30min.
translated_ids_df = translate_userids(evaluation_dataset_characteristics_user_topologies_df, 
                                      num_rows=evaluation_dataset_characteristics_user_topologies_df.shape[0])

100%|██████████| 1585/1585 [19:57<00:00,  1.32rows/s]

#### Calculate the popularity of each user's interactions

In [3]:
def get_all_users_popularity(num_datasets):    
    
    # Initialize DataFrame with pre-defined size and columns
    df = pd.DataFrame({'dataset': range(1, num_datasets + 1)})        
    df['user_popularity'] = [{} for _ in range(num_datasets)]     
    
    # Loop through each dataset and compute user popularity
    for i in tqdm(range(num_datasets)):
        FILENAME = PROJECT_DIRECTORY / f"asset/data/real-life-atomic-splits/real-life-atomic-100000-{i+1}/real-life-atomic-100000-{i+1}.inter"
        db = pd.read_csv(FILENAME, sep="\t", encoding="utf-8")
        
        # Filter users with less than 20 interactions
        db['interaction_count'] = db.groupby("userID:token")["itemID:token"].transform('count')
        filtered_df = db[db['interaction_count'] >= 20].copy()
        
        # Calculate item popularity
        item_popularity = filtered_df.groupby("itemID:token")["userID:token"].nunique()
        
        # Map item popularity back to filtered_df safely
        filtered_df.loc[:, 'item_popularity'] = filtered_df["itemID:token"].map(item_popularity)
        
        # Compute user average popularity
        user_avg_popularity = filtered_df.groupby("userID:token")['item_popularity'].agg(['mean', 'median'])
        
        # Compute user popularity dictionary
        all_users_popularity_dict = {
            user_id: (row['mean'], row['median']) 
            for user_id, row in user_avg_popularity.iterrows()
        }
        
        # Assign the dictionary to the DataFrame
        df.at[i,'user_popularity'] = all_users_popularity_dict
    
    return df

In [4]:
# HINT: takes approx. 1min
file_path = "../asset/Evaluation/UserAveragePopularity.csv"
if not os.path.isfile(file_path):
    print("File does not exist, calculate all user's popularity for each dataset..")
    popularity_dict = get_all_users_popularity(num_datasets=177)
    popularity_dict.to_csv(file_path, sep='\t', index=False)
else:
    print(f"File exists! Load file from {file_path}")
    # Load the existing DataFrame
    popularity_dict = pd.read_csv(file_path, sep='\t') 
    # Convert the user_popularity column back to dictionaries
    if 'user_popularity' in popularity_dict.columns:
        popularity_dict['user_popularity'] = popularity_dict['user_popularity'].apply(ast.literal_eval)

File does not exist, calculate all user's popularity for each dataset..

100%|██████████| 177/177 [00:30<00:00,  5.85it/s]

In [5]:
print(popularity_dict.head())

   dataset                                    user_popularity
0        1  {1: (9.698447893569845, 4.0), 2: (3.44, 2.0), ...
1        2  {1: (21.978021978021978, 3.0), 2: (23.41304347...
2        3  {1: (16.871382636655948, 3.0), 2: (16.64761904...
3        4  {1: (7.957446808510638, 4.0), 5: (5.28125, 4.0...
4        5  {1: (34.275, 4.0), 4: (11.0, 3.0), 5: (22.3975...

In [75]:
def get_user_popularity(data, all_users_popularity_dict, num_rows):
    
    df = data.copy()
    
    # Initialize new columns with empty lists
    df['best_users_mean_popularity_dict'] = [{} for _ in range(len(df))]
    df['best_users_mean_popularity_mean'] = [{} for _ in range(len(df))]
    df['best_users_mean_popularity_max'] = [{} for _ in range(len(df))]
    df['best_users_mean_popularity_min'] = [{} for _ in range(len(df))]    
    df['best_users_median_popularity_dict'] = [{} for _ in range(len(df))]
    df['best_users_median_popularity_mean'] = [{} for _ in range(len(df))]
    df['best_users_median_popularity_max'] = [{} for _ in range(len(df))]
    df['best_users_median_popularity_min'] = [{} for _ in range(len(df))]
    df['best_users_node_degree_dict'] = [{} for _ in range(len(df))]
    df['best_users_node_degree_mean'] = [{} for _ in range(len(df))]
    df['best_users_node_degree_median'] = [{} for _ in range(len(df))]
    df['best_users_node_degree_min'] = [{} for _ in range(len(df))]
    df['best_users_node_degree_max'] = [{} for _ in range(len(df))]

    df['worst_users_mean_popularity_dict'] = [{} for _ in range(len(df))]
    df['worst_users_mean_popularity_mean'] = [{} for _ in range(len(df))]
    df['worst_users_mean_popularity_max'] = [{} for _ in range(len(df))]
    df['worst_users_mean_popularity_min'] = [{} for _ in range(len(df))]    
    df['worst_users_median_popularity_dict'] = [{} for _ in range(len(df))]
    df['worst_users_median_popularity_mean'] = [{} for _ in range(len(df))]
    df['worst_users_median_popularity_max'] = [{} for _ in range(len(df))]
    df['worst_users_median_popularity_min'] = [{} for _ in range(len(df))]
    df['worst_users_node_degree_dict'] = [{} for _ in range(len(df))]
    df['worst_users_node_degree_mean'] = [{} for _ in range(len(df))]
    df['worst_users_node_degree_median'] = [{} for _ in range(len(df))]
    df['worst_users_node_degree_min'] = [{} for _ in range(len(df))]
    df['worst_users_node_degree_max'] = [{} for _ in range(len(df))]

    df['all_users_median_popularity_mean'] = [{} for _ in range(len(df))]
    df['all_users_median_popularity_max'] = [{} for _ in range(len(df))]
    df['all_users_median_popularity_min'] = [{} for _ in range(len(df))]
    df['all_users_node_degree_mean'] = [{} for _ in range(len(df))]
    df['all_users_median_node_degree_median'] = [{} for _ in range(len(df))]
    df['all_users_node_degree_max'] = [{} for _ in range(len(df))]
    df['all_users_node_degree_min'] = [{} for _ in range(len(df))]    
     
    # Loop through each row
    for index, row in tqdm(df.iloc[:num_rows].iterrows(), total=num_rows, unit='rows'):

        # configurations initialization
        FILENAME = PROJECT_DIRECTORY / f"asset/data/real-life-atomic-splits/real-life-atomic-100000-{row['dataset']}/real-life-atomic-100000-{row['dataset']}.inter"
        db = pd.read_csv(FILENAME, sep="\t", encoding="utf-8")
        
        # Filter users with less than 20 node_degree
        db['interaction_count'] = db.groupby("userID:token")["itemID:token"].transform('count')
        filtered_df = db[db['interaction_count'] >= 20].copy()
        all_users_node_degree_dict = filtered_df.groupby("userID:token")['interaction_count'].first()
                        
        # Extract unique user IDs from best_user_ and worst_user_ columns
        best_user_ids = set()  # Use a set to ensure uniqueness
        worst_user_ids = set()  # Use a set to ensure uniqueness
        for col in df.columns:
            if col.startswith('best_user_'):
                # Extract user IDs from the list of dictionaries
                for entry in row[col].keys(): 
                    best_user_ids.add(int(entry))  # Add user ID (the key) to the set
            if col.startswith('worst_user_'):
                # Extract user IDs from the list of dictionaries
                for entry in row[col].keys():  # Assuming each entry is a list of dictionaries
                    worst_user_ids.add(int(entry))  # Add user ID (the key) to the set
                                         
        # Prepare best users
        best_users_mean_popularity_dict = {str(user_id): all_users_popularity_dict.loc[row['dataset']-1,'user_popularity'][user_id][0] for user_id in best_user_ids}
        best_users_median_popularity_dict = {str(user_id): all_users_popularity_dict.loc[row['dataset']-1,'user_popularity'][user_id][1] for user_id in best_user_ids}
        best_users_node_degree_dict = {str(user_id): all_users_node_degree_dict[user_id] for user_id in best_user_ids}     
        best_users_mean_values_list = list(best_users_mean_popularity_dict.values())
        best_users_median_values_list = list(best_users_median_popularity_dict.values())
        best_users_node_degree_list = list(best_users_node_degree_dict.values())

        worst_users_mean_popularity_dict = {str(user_id): all_users_popularity_dict.loc[row['dataset']-1,'user_popularity'][user_id][0] for user_id in worst_user_ids}
        worst_users_median_popularity_dict = {str(user_id): all_users_popularity_dict.loc[row['dataset']-1,'user_popularity'][user_id][1] for user_id in worst_user_ids}
        worst_users_node_degree_dict = {str(user_id): all_users_node_degree_dict[user_id] for user_id in worst_user_ids}     
        worst_users_mean_values_list = list(worst_users_mean_popularity_dict.values())
        worst_users_median_values_list = list(worst_users_median_popularity_dict.values())
        worst_users_node_degree_list = list(worst_users_node_degree_dict.values())
        
        all_users_mean_values_list = [entry[0] for entry in list(all_users_popularity_dict.loc[row['dataset']-1,'user_popularity'].values())]
        all_users_median_values_list = [entry[1] for entry in list(all_users_popularity_dict.loc[row['dataset']-1,'user_popularity'].values())]

        # Assign
        df.at[index, 'best_users_mean_popularity_dict'] = best_users_mean_popularity_dict
        df.at[index, 'best_users_mean_popularity_mean'] = np.mean(best_users_mean_values_list)
        df.at[index, 'best_users_mean_popularity_max'] = np.max(best_users_mean_values_list)
        df.at[index, 'best_users_mean_popularity_min'] = np.min(best_users_mean_values_list)
        df.at[index, 'best_users_median_popularity_dict'] = best_users_median_popularity_dict
        df.at[index, 'best_users_median_popularity_mean'] = np.mean(best_users_median_values_list)
        df.at[index, 'best_users_median_popularity_max'] = np.max(best_users_median_values_list)
        df.at[index, 'best_users_median_popularity_min'] = np.min(best_users_median_values_list)
        df.at[index, 'best_users_node_degree_dict'] = best_users_node_degree_dict
        df.at[index, 'best_users_node_degree_mean'] = np.mean(best_users_node_degree_list)
        df.at[index, 'best_users_node_degree_median'] = np.median(best_users_node_degree_list)
        df.at[index, 'best_users_node_degree_min'] = np.min(best_users_node_degree_list)
        df.at[index, 'best_users_node_degree_max'] = np.max(best_users_node_degree_list)

        df.at[index, 'worst_users_mean_popularity_dict'] = worst_users_mean_popularity_dict
        df.at[index, 'worst_users_mean_popularity_mean'] = np.mean(worst_users_mean_values_list)
        df.at[index, 'worst_users_mean_popularity_max'] = np.max(worst_users_mean_values_list)
        df.at[index, 'worst_users_mean_popularity_min'] = np.min(worst_users_mean_values_list)
        df.at[index, 'worst_users_median_popularity_dict'] = worst_users_median_popularity_dict
        df.at[index, 'worst_users_median_popularity_mean'] = np.mean(worst_users_median_values_list)
        df.at[index, 'worst_users_median_popularity_max'] = np.max(worst_users_median_values_list)
        df.at[index, 'worst_users_median_popularity_min'] = np.min(worst_users_median_values_list)
        df.at[index, 'worst_users_node_degree_dict'] = worst_users_node_degree_dict
        df.at[index, 'worst_users_node_degree_mean'] = np.mean(worst_users_node_degree_list)
        df.at[index, 'worst_users_node_degree_median'] = np.median(worst_users_node_degree_list)
        df.at[index, 'worst_users_node_degree_min'] = np.min(worst_users_node_degree_list)
        df.at[index, 'worst_users_node_degree_max'] = np.max(worst_users_node_degree_list)

        df.at[index, 'all_users_mean_popularity_mean'] = np.mean(all_users_mean_values_list)
        df.at[index, 'all_users_mean_popularity_max'] = np.max(all_users_mean_values_list)
        df.at[index, 'all_users_mean_popularity_min'] = np.min(all_users_mean_values_list)
        df.at[index, 'all_users_median_popularity_mean'] = np.mean(all_users_median_values_list)
        df.at[index, 'all_users_median_popularity_max'] = np.max(all_users_median_values_list)
        df.at[index, 'all_users_median_popularity_min'] = np.min(all_users_median_values_list)
        df.at[index, 'all_users_node_degree_mean'] = all_users_node_degree_dict.mean()
        df.at[index, 'all_users_median_node_degree_median'] = all_users_node_degree_dict.median()
        df.at[index, 'all_users_node_degree_max'] = all_users_node_degree_dict.max()
        df.at[index, 'all_users_node_degree_min'] = all_users_node_degree_dict.min()
        
    return df

In [5]:
# NOTE: takes approx. 2-3 min
file_path = "../asset/Evaluation/UserAveragePopularity_tmp.csv"
#classical_user_characteristics_df = get_user_popularity(translated_ids_df, popularity_dict, num_rows = translated_ids_df.shape[0])
classical_user_characteristics_df = pd.read_csv(file_path, sep='\t')
#classical_user_characteristics_df.to_csv(file_path, sep='\t', index=False)

In [101]:
final_eval_df = pd.merge(translated_ids_df, classical_user_characteristics_df, on=['dataset', 'Model'], how='left')

In [6]:
classical_user_characteristics_df['best_user_mrr@[10]']

0       {'1173': 1.0, '3436': 1.0, '1787': 1.0, '840':...
1       {'4140': 1.0, '4974': 1.0, '6319': 1.0, '3929'...
2       {'8887': 1.0, '698': 1.0, '7471': 1.0, '726': ...
3       {'2401': 1.0, '11012': 1.0, '11017': 1.0, '358...
4       {'12768': 1.0, '12490': 1.0, '1723': 1.0, '118...
                              ...
1580    {'2508': 1.0, '12824': 1.0, '4853': 1.0, '3679...
1581    {'11061': 1.0, '64235': 1.0, '2222': 1.0, '257...
1582    {'12416': 1.0, '10179': 1.0, '847': 1.0, '2599...
1583    {'20452': 1.0, '872': 1.0, '15182': 1.0, '2936...
1584    {'7612': 1.0, '4655': 1.0, '53514': 1.0, '6964...
Name: best_user_mrr@[10], Length: 1585, dtype: object

In [102]:
final_eval_df

,Model,dataset,precision@10_x,hit@10_x,mrr@10_x,ndcg@10_x,map@10_x,itemcoverage@10_x,averagepopularity@10_x,tailpercentage@10_x,...,all_users_median_popularity_mean,all_users_median_popularity_max,all_users_median_popularity_min,all_users_node_degree_mean,all_users_median_node_degree_median,all_users_node_degree_max,all_users_node_degree_min,all_users_mean_popularity_mean,all_users_mean_popularity_max,all_users_mean_popularity_min
0,ALS,1,0.1477,0.5705,0.3160,0.1880,0.1190,0.0814,50.0136,0.0000,...,26.724254,125.0,1.0,78.673725,42.0,2395,20,36.897370,137.333333,1.285714
1,ALS,2,0.1371,0.5733,0.3047,0.1806,0.1100,0.0611,59.3676,0.0000,...,34.844812,164.5,1.0,72.411387,37.0,10246,20,47.007209,151.090909,1.440000
2,ALS,3,0.1366,0.5848,0.3046,0.1808,0.1079,0.0759,76.0369,0.0000,...,49.369912,195.5,1.0,58.525938,35.0,1514,20,67.559298,207.950000,1.427273
3,ALS,4,0.1359,0.5658,0.2893,0.1695,0.1003,0.0746,57.4025,0.0004,...,27.319709,188.5,1.5,75.170754,40.0,3311,20,41.676556,172.000000,2.333333
4,ALS,5,0.1410,0.5718,0.3177,0.1861,0.1157,0.0827,51.7001,0.0005,...,28.002395,161.0,1.0,78.244253,39.0,7556,20,39.797047,145.500000,2.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1580,Pop,173,0.0390,0.2105,0.0929,0.0480,0.0237,0.0024,108.9045,0.0000,...,35.878603,163.0,1.0,68.815721,39.0,1863,20,46.923704,157.760000,1.240000
1581,Pop,174,0.0386,0.2631,0.0841,0.0435,0.0174,0.0027,129.1384,0.0000,...,41.593005,187.5,1.0,59.062003,37.0,1319,20,56.389108,194.136364,1.350000
1582,Pop,175,0.0408,0.2607,0.1094,0.0517,0.0241,0.0023,111.9991,0.0000,...,24.01676,118.0,1.0,76.06797,40.0,2192,20,33.965654,125.760000,1.150000
1583,Pop,176,0.0403,0.2603,0.1059,0.0508,0.0219,0.0021,122.2490,0.0000,...,35.034675,187.0,1.0,67.946062,38.0,2458,20,46.849503,179.450000,1.363636
1584,Pop,177,0.0503,0.3020,0.1113,0.0620,0.0286,0.0022,155.0318,0.0000,...,44.138707,171.0,1.0,61.63748,36.0,1962,20,61.817694,196.173913,1.223776

In [7]:
# Function to process columns
def json_dumps_user_columns(data):
    df = data.copy()
    for col in df.columns:
        if col.startswith('best_user_') or col.startswith('worst_user_') or col.endswith('dict'):
            # Apply transformation for each row in the selected columns
            df [col] = df[col].apply(json.dumps)
    return df

# Function to process columns
def json_loads_user_columns(data):
    df = data.copy()
    for col in df.columns:
        if col.startswith('best_user_') or col.startswith('worst_user_') or col.endswith('dict'):
            # Apply transformation for each row in the selected columns
            df[col] = df[col].apply(json.loads)
    return df

In [8]:
final_eval_df = json_dumps_user_columns(classical_user_characteristics_df)

best_user_precision@[10]
best_user_hit@[10]
best_user_mrr@[10]
best_user_ndcg@[10]
best_user_map@[10]
worst_user_precision@[10]
worst_user_hit@[10]
worst_user_mrr@[10]
worst_user_ndcg@[10]
worst_user_map@[10]
best_users_mean_popularity_dict
best_users_median_popularity_dict
best_users_node_degree_dict
worst_users_mean_popularity_dict
worst_users_median_popularity_dict
worst_users_node_degree_dict

### Store the files as Parquet

In [9]:
final_eval_df

,Model,dataset,precision@10,hit@10,mrr@10,ndcg@10,map@10,itemcoverage@10,averagepopularity@10,tailpercentage@10,...,all_users_median_popularity_mean,all_users_median_popularity_max,all_users_median_popularity_min,all_users_node_degree_mean,all_users_median_node_degree_median,all_users_node_degree_max,all_users_node_degree_min,all_users_mean_popularity_mean,all_users_mean_popularity_max,all_users_mean_popularity_min
0,ALS,1,0.1477,0.5705,0.3160,0.1880,0.1190,0.0814,50.0136,0.0000,...,26.724254,125.0,1.0,78.673725,42.0,2395,20,36.897370,137.333333,1.285714
1,ALS,2,0.1371,0.5733,0.3047,0.1806,0.1100,0.0611,59.3676,0.0000,...,34.844812,164.5,1.0,72.411387,37.0,10246,20,47.007209,151.090909,1.440000
2,ALS,3,0.1366,0.5848,0.3046,0.1808,0.1079,0.0759,76.0369,0.0000,...,49.369912,195.5,1.0,58.525938,35.0,1514,20,67.559298,207.950000,1.427273
3,ALS,4,0.1359,0.5658,0.2893,0.1695,0.1003,0.0746,57.4025,0.0004,...,27.319709,188.5,1.5,75.170754,40.0,3311,20,41.676556,172.000000,2.333333
4,ALS,5,0.1410,0.5718,0.3177,0.1861,0.1157,0.0827,51.7001,0.0005,...,28.002395,161.0,1.0,78.244253,39.0,7556,20,39.797047,145.500000,2.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1580,Pop,173,0.0390,0.2105,0.0929,0.0480,0.0237,0.0024,108.9045,0.0000,...,35.878603,163.0,1.0,68.815721,39.0,1863,20,46.923704,157.760000,1.240000
1581,Pop,174,0.0386,0.2631,0.0841,0.0435,0.0174,0.0027,129.1384,0.0000,...,41.593005,187.5,1.0,59.062003,37.0,1319,20,56.389108,194.136364,1.350000
1582,Pop,175,0.0408,0.2607,0.1094,0.0517,0.0241,0.0023,111.9991,0.0000,...,24.016760,118.0,1.0,76.067970,40.0,2192,20,33.965654,125.760000,1.150000
1583,Pop,176,0.0403,0.2603,0.1059,0.0508,0.0219,0.0021,122.2490,0.0000,...,35.034675,187.0,1.0,67.946062,38.0,2458,20,46.849503,179.450000,1.363636
1584,Pop,177,0.0503,0.3020,0.1113,0.0620,0.0286,0.0022,155.0318,0.0000,...,44.138707,171.0,1.0,61.637480,36.0,1962,20,61.817694,196.173913,1.223776

In [14]:
file_path = f"../asset/Evaluation/{EVAL_RUN}/EvaluationData.parquet"
final_eval_df = classical_user_characteristics_df[classical_user_characteristics_df['dataset'] != 177]
final_eval_df.to_parquet(file_path, engine="pyarrow", index=False)

### Load the files from Parquet

In [15]:
file_path = f"../asset/Evaluation/{EVAL_RUN}/EvaluationData.parquet"
if not os.path.isfile(file_path):
    print("File does not exist, please run all the lines above..")
else:
    print(f"File exists! Load file from {file_path}")
    # Load the existing DataFrame
    final_eval_df = pd.read_parquet(file_path, engine="pyarrow")
    #final_eval_df = json_loads_user_columns(final_eval_df)

File exists! Load file from ../asset/Evaluation/RO/EvaluationData.parquet

In [17]:
final_eval_df = json_loads_user_columns(final_eval_df)

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

In [18]:
final_eval_df

,Model,dataset,precision@10,hit@10,mrr@10,ndcg@10,map@10,itemcoverage@10,averagepopularity@10,tailpercentage@10,...,all_users_median_popularity_mean,all_users_median_popularity_max,all_users_median_popularity_min,all_users_node_degree_mean,all_users_median_node_degree_median,all_users_node_degree_max,all_users_node_degree_min,all_users_mean_popularity_mean,all_users_mean_popularity_max,all_users_mean_popularity_min
0,ALS,1,0.1477,0.5705,0.3160,0.1880,0.1190,0.0814,50.0136,0.0000,...,26.724254,125.0,1.0,78.673725,42.0,2395,20,36.897370,137.333333,1.285714
1,ALS,2,0.1371,0.5733,0.3047,0.1806,0.1100,0.0611,59.3676,0.0000,...,34.844812,164.5,1.0,72.411387,37.0,10246,20,47.007209,151.090909,1.440000
2,ALS,3,0.1366,0.5848,0.3046,0.1808,0.1079,0.0759,76.0369,0.0000,...,49.369912,195.5,1.0,58.525938,35.0,1514,20,67.559298,207.950000,1.427273
3,ALS,4,0.1359,0.5658,0.2893,0.1695,0.1003,0.0746,57.4025,0.0004,...,27.319709,188.5,1.5,75.170754,40.0,3311,20,41.676556,172.000000,2.333333
4,ALS,5,0.1410,0.5718,0.3177,0.1861,0.1157,0.0827,51.7001,0.0005,...,28.002395,161.0,1.0,78.244253,39.0,7556,20,39.797047,145.500000,2.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,Pop,172,0.0297,0.2131,0.0712,0.0368,0.0152,0.0015,96.8660,0.0000,...,25.164953,120.5,1.0,76.462617,41.0,2072,20,34.876773,128.500000,1.130435
1580,Pop,173,0.0390,0.2105,0.0929,0.0480,0.0237,0.0024,108.9045,0.0000,...,35.878603,163.0,1.0,68.815721,39.0,1863,20,46.923704,157.760000,1.240000
1581,Pop,174,0.0386,0.2631,0.0841,0.0435,0.0174,0.0027,129.1384,0.0000,...,41.593005,187.5,1.0,59.062003,37.0,1319,20,56.389108,194.136364,1.350000
1582,Pop,175,0.0408,0.2607,0.1094,0.0517,0.0241,0.0023,111.9991,0.0000,...,24.016760,118.0,1.0,76.067970,40.0,2192,20,33.965654,125.760000,1.150000
1583,Pop,176,0.0403,0.2603,0.1059,0.0508,0.0219,0.0021,122.2490,0.0000,...,35.034675,187.0,1.0,67.946062,38.0,2458,20,46.849503,179.450000,1.363636